In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
train=pd.read_csv("C:/Users/Parvathy Narippatta/Downloads/archive (4)/train.csv")
test=pd.read_csv("C:/Users/Parvathy Narippatta/Downloads/archive (4)/test.csv")


In [2]:
train.shape

(491, 13)

In [3]:
test.shape

(123, 13)

In [4]:
train['LoanAmount_log']=np.log(train['LoanAmount'])
test['LoanAmount_log']=np.log(test['LoanAmount'])

In [5]:
train.isnull().sum()

Loan_ID               0
Gender                9
Married               3
Dependents           12
Education             0
Self_Employed        27
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           18
Loan_Amount_Term     14
Credit_History       39
Property_Area         0
Loan_Status           0
LoanAmount_log       18
dtype: int64

In [6]:
test.isnull().sum()

Loan_ID               0
Gender                4
Married               0
Dependents            3
Education             0
Self_Employed         5
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            4
Loan_Amount_Term      0
Credit_History       11
Property_Area         0
Loan_Status           0
LoanAmount_log        4
dtype: int64

In [7]:
train['Gender'].fillna(train['Gender'].mode()[0],inplace=True)
test['Gender'].fillna(test['Gender'].mode()[0],inplace=True)

In [8]:
train['Married'].fillna(train['Married'].mode()[0],inplace=True)

In [9]:
train['Dependents'].fillna(train['Dependents'].mode()[0],inplace=True)

In [10]:
test['Dependents'].fillna(test['Dependents'].mode()[0],inplace=True)

In [11]:
train['Self_Employed'].fillna(train['Self_Employed'].mode()[0],inplace=True)
test['Self_Employed'].fillna(test['Self_Employed'].mode()[0],inplace=True)

In [12]:
train.LoanAmount=train.LoanAmount.fillna(train.LoanAmount_log.mean())
train.LoanAmount_log=train.LoanAmount_log.fillna(train.LoanAmount_log.mean())
test.LoanAmount=test.LoanAmount.fillna(test.LoanAmount_log.mean())
test.LoanAmount_log=test.LoanAmount_log.fillna(test.LoanAmount_log.mean())


In [13]:
test['Loan_Amount_Term'].fillna(test['Loan_Amount_Term'].mode()[0],inplace=True)

In [14]:
test['Credit_History'].fillna(test['Credit_History'].mode()[0],inplace=True)

In [15]:
train['Loan_Amount_Term'].fillna(train['Loan_Amount_Term'].mode()[0],inplace=True)

In [16]:
train['Credit_History'].fillna(train['Credit_History'].mode()[0],inplace=True)

In [17]:
train.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
LoanAmount_log       0
dtype: int64

In [18]:
test.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
LoanAmount_log       0
dtype: int64

In [19]:
train['TotalIncome']=train['ApplicantIncome']+train['CoapplicantIncome']
train['TotalIncome_log']=np.log(train['TotalIncome'])
test['TotalIncome']=test['ApplicantIncome']+test['CoapplicantIncome']
test['TotalIncome_log']=np.log(test['TotalIncome'])

In [20]:
x_train=train.iloc[:,np.r_[1:5,9:11,13:15]].values
y_train=train.iloc[:,12].values

x_test=test.iloc[:,np.r_[1:5,9:11,13:15]].values
y_test=test.iloc[:,12].values

In [21]:
x_train[1]

array(['Male', 'Yes', '1', 'Graduate', 360.0, 1.0, 4.852030263919617,
       6091.0], dtype=object)

In [22]:
from sklearn.preprocessing import LabelEncoder
labelencoder_x=LabelEncoder()

In [23]:
for i in range(0,5):
    x_train[:,i]= labelencoder_x.fit_transform(x_train[:,i])

In [24]:
#x_train[:,7]=labelencoder_x.fit_transform(x_train[:,7])

In [25]:
labelencoder_y=LabelEncoder()

In [26]:
y_train

array(['Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y',
       'N', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'Y', 'N', 'N', 'N', 'Y',
       'Y', 'Y', 'N', 'Y', 'N', 'N', 'N', 'Y', 'N', 'Y', 'N', 'Y', 'Y',
       'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y',
       'N', 'N', 'N', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N',
       'N', 'N', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'N', 'N',
       'N', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y',
       'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N',
       'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'N', 'N', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'N',
       'Y', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'N', 'Y', 'N', 'N

In [27]:
y_train= labelencoder_y.fit_transform(y_train)

In [28]:
x_train[0]

array([1, 0, 0, 0, 7, 1.0, 4.849685489173536, 5849.0], dtype=object)

In [29]:
y_train

array([1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,

In [30]:
for i in range(0,5):
    x_test[:,i]= labelencoder_x.fit_transform(x_test[:,i])

In [31]:
#x_test[:,7]=labelencoder_x.fit_transform(x_test[:,7])

In [32]:
y_test= labelencoder_y.fit_transform(y_test)

In [33]:
#from sklearn.preprocessing import StandardScaler
#ss=StandardScaler()
#x_train=ss.fit_transform(x_train)
#x_test=ss.fit_transform(x_test)


In [34]:
x_train[1]

array([1, 1, 1, 0, 7, 1.0, 4.852030263919617, 6091.0], dtype=object)

In [35]:
from sklearn.tree import DecisionTreeClassifier
DTClassifier=DecisionTreeClassifier(criterion='entropy',random_state=0)
DTClassifier.fit(x_train, y_train)

C:\Users\Parvathy Narippatta\Anaconda3\lib\site-packages\sklearn\linear_model\least_angle.py:30: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  method='lar', copy_X=True, eps=np.finfo(np.float).eps,
C:\Users\Parvathy Narippatta\Anaconda3\lib\site-packages\sklearn\linear_model\least_angle.py:167: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations


DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=0, splitter='best')

In [36]:
y_pred= DTClassifier.predict(x_test)

In [37]:
from sklearn import metrics

In [38]:
print('The accuracy of Decision Tree model is: ',metrics.accuracy_score(y_pred,y_test))

The accuracy of Decision Tree model is:  0.7073170731707317


In [39]:
from sklearn.naive_bayes import GaussianNB
NBClassifier=GaussianNB()
NBClassifier.fit(x_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [40]:
y_pred= NBClassifier.predict(x_test)
y_pred

array([1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0])

In [41]:
print('The accuracy of Naive Bayes model is: ',metrics.accuracy_score(y_pred,y_test))

The accuracy of Naive Bayes model is:  0.8292682926829268


In [42]:
import pickle

In [43]:
pickle.dump(NBClassifier, open('eli.pkl', 'wb'))

In [44]:
loaded_model = pickle.load(open('eli.pkl', 'rb'))